### ISSUE TITLE
Некорректно работает метод разбора CSV

### ISSUE THREAD

**Issue by kubk** [codedokode/task-checker#1]
[Метод разбора CSV](https://github.com/codedokode/task-checker/blob/master/src/Module/Util.php#L19) работает некорректно, [пример падающего теста](https://github.com/kubk/task-checker/commit/3973a22dc85843c89d1b9f99a8c826754fcf690d).

Пример на 3v4l.org: https://3v4l.org/CN5rG

По-видимому, проблемы из-за использования ссылок в foreach: https://github.com/codedokode/task-checker/blob/master/src/Module/Util.php#L26
Объяснения (немного запутанные): https://stackoverflow.com/questions/3307409/php-pass-by-reference-in-foreach

Пути обхода:
1) Использовать unset на каждой итерации цикла:
```php
foreach ($data as &$row) {
    $row = array_map('trim', $row);
    unset($row);
}
```

2) Взять готовое решение для парсинга CSV.

**Comment by codedokode** [comment]
Да, верно, проблема была в том, что в `$row` осталась ссылка на последний элемент и позже в него что-то было записано по этой ссылке. Надо либо делать `unset` после цикла, либо не использовать ссылки.

Убрал ссылку, добавил тест.

> Взять готовое решение для парсинга CSV.

Там уже используется `str_getcsv`, большая часть кода просто переводит данные в нужный формат и проверяет правильность. 

Спасибо за сообщение.
